# Generated by Django 6.1.1 on 2026-09-16 18:25

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('info', 'Info'), ('submission', 'Submission'), ('danger', 'Danger'), ('safe', 'Safe')], default='info', max_length=16)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'activity log entry',
                'verbose_name_plural': 'activity log',
                'ordering': ['-timestamp', '-id'],
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(default=core.models.default_zone_id, max_length=64, unique=True)),
                ('kind', models.CharField(choices=[('danger', 'Danger zone'), ('safe', 'Safe zone')], default='danger', max_length=8)),
                ('name', models.CharField(max_length=120)),
                ('vertices', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'zone',
                'verbose_name_plural': 'zones',
                'ordering': ['kind', 'name'],
            },
        ),
    ]
